#!/usr/bin/env bash

names=(duangduang Saigyouji-Yuyuko dd Alex Kamikakushi jordi abel jojo Yescafe leo nonmean)
tmp_file="__tmp__file__stats"

if [ -f "$tmp_file" ]; then
    echo "File $tmp_file exists"
    exit 1
fi

for name in ${names[@]}
do
    cnt=`find . -type f -name "$name.*" | wc -l | xargs`
    printf "%3d : $name\n" $cnt >> $tmp_file
done

sort -k 1 -n -r $tmp_file
rm ./$tmp_file
